### ISSUE TITLE
Fix: Gordon update fail

### ISSUE THREAD

**Issue by alessiopellindgm** [EOS-Solutions/Gordon#124]
# 🐛 Bug Report

Installing the update from version 1.1.25 to 1.1.26 I get this error:
![image](https://github.com/user-attachments/assets/10811efb-8d82-4d32-81a7-8d65f24a7347)

Doing both "update" gives me the same error while doing "uninstall" gives me "Uninstalled Successfully".

At this moment Gordon's folder "%appdata%\Local\Programs\EOS Solutions\Gordon" has been deleted (not sure if during update or uninstall)

I attach all the logs of the apps in question:
Gordon:
[debug.txt](https://github.com/user-attachments/files/17296017/debug.txt)

Gordon Installer:
[gordon-installer-deploy.log](https://github.com/user-attachments/files/17296026/gordon-installer-deploy.log)
[gordon-deploy.log](https://github.com/user-attachments/files/17296027/gordon-deploy.log)
[gordon-installer.log](https://github.com/user-attachments/files/17296028/gordon-installer.log)

## Product
- [x] Gordon (Version: 1.1.25)
- [x] EOS Gordon Installer (Version: 0.0.112.0)

**Comment by alessiopellindgm** [comment]
Update.
I rebooted the machine and, using "uninstall", Gordon Installer sees the app actually uninstalled.

When I reinstalled it the antivirus blocked the installation of the app (open new ticker #126 )

To install app, the only way that worked is:
- Delete app folder
- Restart machine
- Uninstall app from Gordon Installer
- Disable antivirus
- Install app.

**Comment by Thomas-Torggler-EOS** [comment]
It could be that a failed update might leave your installation in an undefined state. Some files might have been copied, others not. But it does not completely delete the installation. That is surely because of the uninstall.

As for the download error: we discovered a problem with the azure storage account where the files are hosted. Whenever a new version is uploaded, the storage seems to return only partial ZIP (and thus corrupt) files for the first few download attempts. This is the reason for your "could not read block" error. We have now implemented a retry-mechanism that attempts the download multiple times in case it fails or downloads a corrupt ZIP file. This should solve that issue.
