### ISSUE TITLE
Fix: NST Services installed as "Is Instance" are not shown by Gordon

### ISSUE THREAD

**Issue by Luigi-Valente-EOS** [EOS-Solutions/Gordon#159]
# 🐛 Bug Report
Gordon shows only one service on the services list, but I have five services installed.
Probably because the other services are installed as "Is Instance":
![image](https://github.com/user-attachments/assets/d3912010-8f36-42f2-9e57-542df3488c5a)

## Product
- [ ] Gordon (Version: 1.1.38.0)
- [ ] Gordon Powershell (Version: _WriteHereTheVersion_)
- [ ] Gordon Service (Version:3.0.22.0)
- [ ] Gordon Xliff Editor
- [ ] EOS Gordon Installer

**Comment by Stefano-Primo-EOS** [comment]
The problem here is that the Executable of the BC service isn't escaped. 
To fix this, you need to change that. 

from CMD (as Administrator). _do not use powershell as it will not find any services_

#### Get the service details
`sc qc MicrosoftDynamicsNavServer$BC` (substitute MicrosoftDynamicsNavServer$BC with your service name)
this will output something like this: 

```
C:\>sc qc MicrosoftDynamicsNavServer$BC
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: MicrosoftDynamicsNavServer$BC
        TYPE               : 10  WIN32_OWN_PROCESS
        START_TYPE         : 3   DEMAND_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : C:\Program Files\Microsoft Dynamics NAV\240\Service\Microsoft.Dynamics.Nav.Server.exe $BC /config "C:\Program Files\Microsoft Dynamics NAV\240\Service\Microsoft.Dynamics.Nav.Server.exe.config"
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : Dynamics 365 Business Central Server [BC]
        DEPENDENCIES       : HTTP
        SERVICE_START_NAME : NT AUTHORITY\SYSTEM
```

Get the BINARY_PATH_NAME  value and edit it as follows: 
Enclose all within " (double quotes) 
Enclose the path to the Microsoft.Dynamics.Nav.Server.exe within " (double quotes)

from this: 
`C:\Program Files\Microsoft Dynamics NAV\240\Service\Microsoft.Dynamics.Nav.Server.exe $BC /config "C:\Program Files\Microsoft Dynamics NAV\240\Service\Microsoft.Dynamics.Nav.Server.exe.config"`

to this
`""C:\Program Files\Microsoft Dynamics NAV\240\Service\Microsoft.Dynamics.Nav.Server.exe" $BC /config "C:\Program Files\Microsoft Dynamics NAV\240\Service\Microsoft.Dynamics.Nav.Server.exe.config""`

Now escape the internal " (double quotes) like this
`"\"C:\Program Files\Microsoft Dynamics NAV\240\Service\Microsoft.Dynamics.Nav.Server.exe\" $BC /config \"C:\Program Files\Microsoft Dynamics NAV\240\Service\Microsoft.Dynamics.Nav.Server.exe.config\""`


Now you can edit your service like this **(Make sure the service is stopped)**: 
`sc config MicrosoftDynamicsNavServer$BC binPath= "\"C:\Program Files\Microsoft Dynamics NAV\240\Service\Microsoft.Dynamics.Nav.Server.exe\" $BC /config \"C:\Program Files\Microsoft Dynamics NAV\240\Service\Microsoft.Dynamics.Nav.Server.exe.config\""`

Make sure that after the = you add a space!
