### ISSUE TITLE
Help: Function API Log

### ISSUE THREAD

**Issue by alessiopellindgm** [EOS-Solutions/Gordon#165]
# 🚑 Help Request

Previous request https://github.com/EOS-Solutions/Gordon/issues/144

I am asking for some information because I am not an expert in Azure Application Insights.

In Function API, I see that the field must contain a specific key...
![image](https://github.com/user-attachments/assets/5f0e192c-36d0-42c5-91db-233d6d29840c)

Is the Function API configured to send logs only to EOS Azure servers?
Is there any public documentation on how to manage these logs?
Is there a possibility to have details on the structure of the logs so that we can manage the data that comes to Application Insights from our customers or development environments?

P.s.
I used an issue to ask for information... is it correct (there are only two forms, Fix and Feat)?

**Comment by Thomas-Torggler-EOS** [comment]
Hi. Yes, FunctionAPI only sends logs to Application Insights. You can create an account for (almost) free and it is calculated based on the amount of traffic you generate (=> the amount of data that gets sent to the account).

FunctionAPI does not emit any custom telemetry and logs, it just emits the standard metrics that all ASP.NET Core applications emit. This includes telemetry per single request, timings, errors and much more. It is highly configurable and I would suggest to read through the official MS documentation because this is nothing developed or maintained by EOS.

https://learn.microsoft.com/it-it/azure/azure-monitor/app/app-insights-overview
